### PR TITLE
Filter functionality in inbox and sent items

### PR DESCRIPTION
**Pull request by bivashpandey**
Screen Shot 2020-12-01 at 10 45 50 PM

### CODE REVIEW

**Review by just1ngray — APPROVED** [review]
I unified our approaches a little bit better in d532671 (and a little bit 2246d1a).
It may also be prudent to move the `getIndices` function into the `./client/utils` folder and rename it to `searchEmails` or something.

The code seems more simple since 2246d1a but feel 100% free to revert back to 3bce66c since it was working nicely already.

**Review by just1ngray — CHANGES_REQUESTED** [review]
I actually think I should have not approved this until you've provided input to my comments. Sorry!

**Comment by bivashpandey** [comment]
> I actually think I should have not approved this until you've provided input to my comments. Sorry!

It looks really nice and clean now. You don't have to be sorry.

**Review by just1ngray — APPROVED** [review]
Cool stuff

**Pull request merged**
