### PR TITLE
Implemented Backend Address Book CRUD

### PR DESCRIPTION
**Pull request by just1ngray**
Minus the U (updating is not possible with this current implementation); overdevelopment means more cost to maintain.

This has not been tested. I recommend:
1. Checkout this branch
2. Implementing & testing front-end/back-end simultaneously
3. Commit and push your changes to this branch (PR will automatically update)
4. Review and approve this PR when the feature is 100% ready

Other workflows may also work. Please let me know if I need to fix any bugs.

Documentation already reflects these changes.

### CODE REVIEW

**Comment by just1ngray** [comment]
@bivashpandey is this ready for review?

**Comment by bivashpandey** [comment]
> @bivashpandey is this ready for review?

Yes, it should be ready.

**Comment by just1ngray** [comment]
After merging into development. We need to add a navbar item in `Layout.js` for "Address Book"

**Review by bivashpandey — APPROVED** [review]
Works perfectly fine.

**Pull request merged**
