### PR TITLE
Commented and Formatted Code

### PR DESCRIPTION
**Pull request by bivashpandey**
Formatted and Commented Code by - Bivash and Jay

### CODE REVIEW

**Review by just1ngray — APPROVED** [review]
Looks like a lot of great style fixes (and even functional fixes such as `className` instead of `class`.
It seems you were missing information for some of the `@author` tags. Specifically, who worked on each section. Was this on purpose?

**Comment by bivashpandey** [comment]
The code that I had pulled from the development branch didn't have the author's information and we didn't know who worked on which one. So, we left it empty for now.

**Comment by JayPatel200** [comment]
How are we planning to have the author's name on each page this time, Justin?

**Comment by just1ngray** [comment]
Oh I see. I guess it’s up to each person to take credit for their work. This can be done over the project’s lifecycle.
We are good to merge?

**Pull request merged**
