### PR TITLE
Advanced Email Display

### PR DESCRIPTION
**Pull request by just1ngray**
- [X]  State improvements
- [X]  Backend bug-fix when an email is sent from account A to account A
- [X]  Emails can be deleted on front-end
- [X]  Emails have the "important" flag (toggle-able)
- [x] Responsive styling
- [x] Alignment

Help! I am struggling to align the `To/From` and `Subject` titles with the `EmailHeader.js` rows. Do we need them?
I also think this PR is struggling with responsiveness on smaller screens. Can @bivashpandey or @JayPatel200 please have a look at this? I specifically ask you two since you've been doing some amazing work with Bulma, but of course anyone is welcome to help.
Anyone wanting to help can message me and/or commit directly to this branch and the PR will automatically update.

Screen Shot 2020-12-06 at 12 41 07 PM

### CODE REVIEW

**Comment by bivashpandey** [comment]
- I guess we might not need "To" and "subject" in the header. We can use "To" in front of the email in the same line(like in Gmail):
To: abc@gmail.com                 Subject
- And for the responsiveness, Jay said that he will work on it.

**Comment by just1ngray** [comment]
> * I guess we might not need "To" and "subject" in the header. We can use "To" in front of the email in the same line(like in Gmail):
>   To: [abc@gmail.com](mailto:abc@gmail.com)                 Subject

I have removed the to/from labels. Looking at gmail and outlook interfaces it seems that they omit these unnecessary details. Maybe @JayPatel200 can come up with a way to make "SENT ITEMS" and "INBOX ITEMS" larger, since for some unknown reason the `<h2>` tag is ineffective...?

**Comment by bivashpandey** [comment]
My new commits fix those issues of SENT ITEMS and INBOX ITEMS (as well as other titles) with some styling in it.

**Comment by just1ngray** [comment]
> My new commits fix those issues of SENT ITEMS and INBOX ITEMS (as well as other titles) with some styling in it.

Referring to #94

**Review by JayPatel200 — APPROVED** [review]
It works! 💪

**Pull request merged**
