### PR TITLE
Root AutoLogin + Navbar Style Improvements

### PR DESCRIPTION
**Pull request by just1ngray**
In this PR:
1. The user will automatically be logged back in if localstorage still has saved credentials
2. Credentials are now properly removed when the user presses log out
3. Generalized the file `StudentLayout.js` to be simply `Layout.js`
4. Improved styling of `Layout.js` navbar. It still doesn't have an "active" style, but it's fine I think
5. A few files have been saved with prettier

Screen Shot 2020-11-24 at 8 22 52 PM

### CODE REVIEW

**Review by JayPatel200 — COMMENTED** [review]
Seems to be great work! 
The login page(index) displays each field and buttons side by side instead of 
Email    PW
Sign in    Create Account
Does that concern right now, though?

**Comment by just1ngray** [comment]
I didn’t realize I changed this, but I guess you’re right.
You’re doing the layout changes for responsive design in #76, right? It can just be changed there?

**Comment by JayPatel200** [comment]
Yea, absolutely!

**Review by JayPatel200 — APPROVED** [review]
Cool!

**Pull request merged**
