### PR TITLE
Specialist Dashboard

### LINKED ISSUE #72: Managed Student Accounts
Our system is supposed to handle multiple registrations of specialists. This implies that there will need to be multiple student accounts as well. Currently, there are only two accounts: `student@autismns.ca` and `specialist@autismns.ca`. Using the `CreateAccount` option, specialists should be able to create and delete managed student accounts on their `Specialist Control Panel`.

1. Specialists should be able to create managed student accounts on their Specialist Control Panel (new page including an implementation in `Layout.js` if the account is a Specialist)
2. This Create Student Account option will ask for all the necessary information to make the appropriate request to the backend server [https://github.com/just1ngray/CSCI3428/wiki/HTTP-Endpoints#post-apispecialiststudent-a](url)
3. Student accounts of the Specialist should be listed here, along with an option to delete the account all together [https://github.com/just1ngray/CSCI3428/wiki/HTTP-Endpoints#delete-apispecialiststudentstudent_id-a](url)

This task includes mostly front-end implementation. Some back-end may have to be added and/or tested.

### PR DESCRIPTION
**Pull request by just1ngray**
Closes #72 and fixed a few bugs.

Notably, the `QuestionManager.js` component will be amazing for controlling all the security question implementations on this website. This may help @nickm0rash with some of your tasks?

Screen Shot 2020-11-30 at 3 42 18 PM
Screen Shot 2020-11-30 at 3 42 25 PM

The HTTP endpoint wiki has been edited to include these changes.

Please give it a review and request any necessary changes. Also, give it a try for yourself in your review!

### CODE REVIEW

**Comment by just1ngray** [comment]
Changes reflected in commit 00ce317
Screen Shot 2020-11-30 at 5 19 41 PM

**Comment by bivashpandey** [comment]
Is the password intentionally made visible?

**Comment by just1ngray** [comment]
> Is the password intentionally made visible?

Here's my inline comment about this concern:
```
// type could be 'password', but that may make the user think this application
// is secure. It's not. It uses HTTP + I'm sure other reasons
```

So yes, the password field is intentionally left visible to promote the idea that the password is not securely handled (especially through HTTP protocol instead of HTTPS).

**Review by bivashpandey — APPROVED** [review]
Nice spacing between UIs and it seems working perfectly.

**Comment by JayPatel200** [comment]
Nice work!

**Pull request merged**
